TestDjango/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('core.urls')), 
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path
from . import views

app_name = "CORE"

urlpatterns = [
    # PRODUCTOS
    path('', views.producto_index, name="producto_index"), #PAGINA PRINCIPAL
    path('producto/agregar', views.producto_create, name="producto_create" ),
    path('producto/<int:producto_id>', views.producto_show, name="producto_show" ),
    path('producto/<int:producto_id>/editar', views.producto_edit, name="producto_edit" ),
    path('producto/<int:producto_id>/eliminar', views.producto_delete, name="producto_delete" ),
    path('producto/buscador', views.producto_search, name="producto_search"),
    path('categoria/<int:categoria_id>/productos', views.productos_por_categoria, name="productos_por_categoria"),

    # REGISTRAR USUARIO
    path('registrarse/', views.register, name="register"),

    # CARRITO
    path('carrito/', views.carrito_index, name="carrito_index"),
    path('carrito/agregar', views.carrito_save, name="carrito_save"),
    path('carrito/clean', views.carrito_clean, name="carrito_clean"),
    path('item_carrito/<int:item_carrito_id>/eliminar', views.item_carrito_delete, name="item_carrito_delete"),

    path('compras', views.compras, name='compras'),
]

core/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Categoria(models.Model):
    id = models.IntegerField(primary_key=True, verbose_name='Id de categoria')
    descripcion = models.CharField(max_length=200, null=True)

    def __str__(self) -> str:
        return f"Id: {self.id} | Descripcion: {self.descripcion}"


class Producto(models.Model):
    id = models.IntegerField(primary_key=True, verbose_name='Id de producto')
    titulo = models.CharField(max_length=50, null=False)
    # Imagen
    imagen = models.FileField(upload_to='productos/')
    descripcion = models.CharField(max_length=200, null=False)
    precio = models.DecimalField(null=False, max_digits=10, decimal_places=2)
    # FK
    categoria = models.ForeignKey(Categoria,on_delete=models.CASCADE, related_name="productos")

    def __str__(self) -> str:
        return f"Id: {self.id} | Titulo: {self.titulo} | Imagen: {self.imagen} | Descripcion: {self.descripcion} | Precio: {self.precio} || Categoria_id: {self.categoria.id} "


class Carrito(models.Model):
    id = models.IntegerField(primary_key=True, verbose_name='Id de carrito')
    usuario = models.ForeignKey(User, on_delete=models.CASCADE, related_name="carrito")
    total = models.DecimalField(null=False, max_digits=10, decimal_places=2)

    def __str__(self) -> str:
        return f"Id: {self.id} | Usuario_id: {self.usuario.id} | Usuario: {self.usuario.username} | Total: {self.total}"


class Carrito_item(models.Model):
    id = models.IntegerField(primary_key=True, verbose_name='Id de Item carrito')
    producto = models.ForeignKey(Producto, on_delete=models.CASCADE) 
    carrito = models.ForeignKey(Carrito, on_delete=models.CASCADE, related_name="items")

    def __str__(self) -> str:
        return f"Id: {self.id} | Producto: {self.producto.titulo} | Carrito_id: {self.carrito.id}"


class Suscripcion(models.Model):
    usuario = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='Suscripcion')
    vigencia = models.BooleanField(default=False) 

    def str(self) -> str:
        return f"Id: {self.pk} | Usuario_id: {self.usuario.id} | User: {self.usuario.username} | Vigencia: {self.vigencia}" 

class Compras(models.Model):
    usuario = models.ForeignKey(User, on_delete=models.CASCADE, related_name= "compras")
    total = models.DecimalField(null=False, max_digits=12, decimal_places=2)
    estado = models.CharField(max_length=100, null=False)

    def str(self) -> str:
        return f"Id: {self.pk} | Usuario_id: {self.usuario.id} | User: {self.usuario.username} | Total: {self.total}  | Estado: {self.estado}"

class Venta_item(models.Model):
    producto = models.ForeignKey(Producto, on_delete=models.CASCADE)
    compras = models.ForeignKey(Compras,on_delete=models.CASCADE ,related_name="items_compras") 

    def str(self) -> str:
        return f"Id: {self.pk} | Producto: {self.producto.titulo} | Compras_id: {self.compras.id}"

core/forms.py
from django import forms
from django.db.models import fields
from .models import Producto
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class UserRegisterForm(UserCreationForm):
    email = forms.EmailField()
    password1 = forms.CharField(widget=forms.PasswordInput)
    password2 = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']

""" 
    PRODUCTO 
"""
class FormProducto(forms.ModelForm):

    class Meta:
        model = Producto
        fields = ('titulo','imagen','descripcion','precio','categoria')
        """ widgets = {
            'titulo': forms.TextInput(),
            'descripcion' : forms.Textarea(),
            'precio' : forms.NumberInput(),
            'imagen' : forms.FileField()
        } """
        """ widgets = {
            'titulo': forms.TextInput(attrs={'class': 'form-control', 'placeholder':'Ingrese el nombre del producto...' , 'required': True}),
            'descripcion' : forms.Textarea(attrs={'class' : 'form-control', 'row' : 3, 'required': True}),
            'precio' : forms.NumberInput(attrs={'class' : 'form-control', 'placeholder':'XXXX.XX', 'required': True}),
            'imagen' : forms.FileField(attrs={'class':'form-control-file', 'id':'imagen', 'placeholder': 'Ingrese la imagen...', 'required': True})
        } """

core/views.py
from django.contrib.auth.models import User
from core.forms import FormProducto
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse
from django.http.response import HttpResponse

from core.models import *
from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages

def register(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            usuario_logeado = User.objects.last()
            messages.success(request, f"El usuario ha sido registrado exitosamente!")
            carrito = Carrito()
            carrito.usuario = usuario_logeado
            carrito.total = 0
            carrito.save()
            suscripcion = Suscripcion()
            suscripcion.usuario = usuario_logeado
            suscripcion.vigencia = False
            suscripcion.save()
            return redirect('CORE:producto_index')
        else:
            messages.success(request, "No se pudo registrar el usuario, vuelva a intenarlo!")

    return render(request, 'registration/register.html')

def producto_index(request):
    productos = Producto.objects.all().order_by("-id")
    
    return render(request, "core/producto/index.html", {
        'categorias' : Categoria.objects.all(),
        #'productos' : productos[3:10] codigo para obtener solo algunos
        'productos' : productos
    })

def producto_create(request):
    categorias = Categoria.objects.all()
    if request.method == "POST":
        categoria_del_producto = Categoria.objects.get(id=request.POST["categoria"])
        form = FormProducto(request.POST, request.FILES, instance=Producto(imagen=request.FILES['imagen'], categoria=categoria_del_producto))   
        if form.is_valid():
            form.save()
            return redirect("CORE:producto_index")
        else:
            return render(request, 'core/producto/create.html', {
                'categorias' : categorias,
                'error_message' : 'Ingreso un campo incorrecto, vuelva a intentar'
            })
    else:
        return render(request, 'core/producto/create.html', {
            'categorias' : categorias
        })

def producto_show(request, producto_id):
    producto =  get_object_or_404(Producto, id=producto_id)

    return render(request, 'core/producto/show.html',{
        'categorias' : Categoria.objects.all(),
        'producto' : producto
    })

def producto_edit(request, producto_id):
    categorias = Categoria.objects.all()
    producto = Producto.objects.get(id=producto_id)

    if request.method == "POST":
        categoria_del_producto = Categoria.objects.get(id=request.POST["categoria"])
        form = FormProducto(request.POST, request.FILES, instance=Producto(imagen=request.FILES['imagen'], categoria=categoria_del_producto))   
        if form.is_valid():
            producto.titulo = request.POST['titulo']
            producto.categoria = categoria_del_producto
            producto.descripcion = request.POST['descripcion']
            producto.imagen = request.FILES['imagen']
            producto.precio = request.POST['precio']
            producto.save()
            return redirect("CORE:producto_index")
        else:
            return render(request, 'core/producto/edit.html', {
                'categorias' : categorias,
                'error_message' : 'Ingreso un campo incorrecto, vuelva a intentar'
            })
    else:
        return render(request, 'core/producto/edit.html',{
            'categorias' : categorias,
            'producto' : producto
        })

def producto_delete(request, producto_id):
    producto = Producto.objects.get(id=producto_id)
    producto.delete()
    return redirect('CORE:producto_index')

def producto_search(request):
    texto_de_busqueda = request.GET["texto"]
    productosPorTitulo = Producto.objects.filter(titulo__icontains = texto_de_busqueda).all()
    productosPorDescripcion = Producto.objects.filter(descripcion__icontains = texto_de_busqueda).all()
    productos = productosPorTitulo | productosPorDescripcion
    return render(request, 'core/producto/search.html',
    {
        'categorias' : Categoria.objects.all(),
        'productos' : productos
    })
  
def productos_por_categoria(request, categoria_id):
    categoria = get_object_or_404(Categoria, id = categoria_id)
    productos = categoria.productos.all()
    return render(request, 'core/producto/search.html',
    {
        'categorias' : Categoria.objects.all(),
        'productos' : productos,
        'categoria' : categoria.descripcion,
    })

def carrito_index(request):
    categorias = Categoria.objects.all()
    usuario_logeado = User.objects.get(username=request.user)
    productos = Carrito.objects.get(usuario=usuario_logeado.id).items.all()

    carrito = Carrito.objects.get(usuario=usuario_logeado.id)
    nuevo_precio_Carrito = 0
    for item in carrito.items.all():
        #validar si es que tiene descuento
        nuevo_precio_Carrito += item.producto.precio

    carrito.total = nuevo_precio_Carrito
    carrito.save()

    if request.method == 'POST':
        compras = Compras()
        compras.usuario = usuario_logeado
        compras.total = carrito.total
        compras.estado = 'Compra confirmada'
        compras.save()

        for item in carrito.items.all():
            producto = Producto.objects.get(id=item.id)
            item_compras = Venta_item()
            item_compras.compras = compras
            item_compras.producto = producto
            item_compras.save()

    carrito.items.all().delete()
    carrito.total = 0
    carrito.save()

    messages.success(request, f"Compra finalizada.")

    return render(request, 'core/carrito/index.html', {
        'categorias' : categorias,
        'usuario' : usuario_logeado,
        'items_carrito' : productos
    })

def carrito_save(request):

    if request.method == 'POST':
        producto = Producto.objects.get(id=request.POST['producto_id'])
        usuario_logeado = User.objects.get(username=request.user)

        #Agregamos el producto
        carrito = Carrito.objects.get(usuario=usuario_logeado.id)
        item_carrito = Carrito_item()
        item_carrito.carrito = carrito
        item_carrito.producto = producto
        item_carrito.save()

        #Sumamos el precio
        carrito.total = producto.precio + carrito.total
        carrito.save()
        messages.success(request, f"El producto {producto.titulo} fue agregado al carrito")
        return redirect("CORE:producto_index")

    else:
        return redirect("CORE:producto_index")

def carrito_clean(request):
    usuario_logeado = User.objects.get(username=request.user)
    carrito = Carrito.objects.get(usuario=usuario_logeado.id)
    carrito.items.all().delete()
    carrito.total = 0
    carrito.save()
    return redirect('CORE:carrito_index')

def item_carrito_delete(request, item_carrito_id):
    item_carrito = Carrito_item.objects.get(id=item_carrito_id)
    carrito = item_carrito.carrito
    
    nuevo_precio_Carrito = 0 - item_carrito.producto.precio
    for item in carrito.items.all():
        nuevo_precio_Carrito += item.producto.precio

    carrito.total = nuevo_precio_Carrito
    item_carrito.delete()
    carrito.save()
    return redirect("CORE:carrito_index")



def compras(request):
    usuario_logeado = User.objects.get(username=request.user)
    compras = usuario_logeado.compras.all

    return render(request, 'core/carrito/compras.html',
    {
        'compras' : compras
    })

core/templates/core/producto/create.html
{% extends 'core/layout.html' %}

{% load static %}

{% block content %}
<div class="row">

    <!-- MENSAJE DE ERROR -->
    {% if error_message %}
    <div class="row">
        <div class="col">
            <strong>{{ error_message }}</strong>
        </div>
    </div>
    {% endif %}

    <div class="col"> 
        <!-- TITULO -->
        <div class="col-12">
            <h3 style="font-family: 'Brush Script MT', cursive; color: white; font-size: 50px; text-align: center;">Agregar producto</h3>
        </div>

        <!-- FORMULARIO -->
        <form action="{% url 'CORE:producto_create' %}" method="post" enctype="multipart/form-data">

            {% csrf_token %}

            <!-- NOMBRE PRODUCTO -->
            <div >
                <input class="form-control" type="text" name="titulo" placeholder="Ingresar nombre del producto: " required>
            </div>
            <br>
            <br>
            <div>

                <!-- IMAGEN -->
                <div >
                    <div class="form-group">
                        <label for="imagen" style="color: white;">Imagen del producto: </label>
                        <input style="color: white;" type="file" class="form-control-file" name="imagen" id="imagen"
                            placeholder="Ingresar imagen" required>
                    </div>
                </div>
                <br>
                <br>
                <div>
                    <!-- CATEGORIA -->
                    <div>
                        <select class="custom-select" name="categoria" required>
                            <option value="" selected>---Seleccione el tipo de producto---</option>
                            {% for categoria in categorias %}
                                <option value="{{ categoria.id }}">{{ categoria.descripcion }}</option>
                            {% endfor %}
                        </select>
                    </div>
                    <br>
                    <br>
                    <!-- DESCRIPCION -->
                    <div>
                        <label for="descripcion" style="color: white;">Descripcion del producto: </label>
                        <textarea class="form-control" name="descripcion" rows="3" required></textarea>
                    </div>
                    <br>
                    <br>
                    <div>
                        <div >
                            <!-- PRECIO -->
                            <div >
                                <div >
                                    <div >
                                        <div style="color: white;">Precio del producto: $</div>
                                    </div>
                                    <input type="number" class="form-control" name="precio" placeholder="XXXX.XX" required>
                                </div>
                            </div>
                            <br>
                            <br>
                            <!-- BOTON -->
                            <div >
                                <button type="submit" class="btn btn-success btn-block" style="background-color: black;">Agregar</button>
                            </div>
                        </div>
                    </div>

                </div>
            </div>
        </form>
    </div>
</div>
{% endblock %}

core/templates/core/producto/edit.html
{% extends 'core/layout.html' %}

{% load static %}

{% block content %}
<section class="row my-5 container mx-auto">

    {% if error_message %}
        <div class="alert alert-danger alert-dismissible fade show col-12" role="alert">
            <strong>{{ error_message }}</strong>
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
    {% endif %}
    {% if okey_message %}
        <div class="alert alert-danger alert-dismissible fade show col-12" role="alert">
            <strong>{{ okey_message }}</strong>
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
    {% endif %}

    <div class="col-12">
        <h3 style="color: white; font-size: 45px; font-family: 'Brush Script MT', cursive;">Editar producto</h3>
    </div>

    <form action="" method="post" enctype="multipart/form-data" class="w-100 col-12">

        {% csrf_token %}
        <div class="col-12 p-0 form-group">
            <input class="form-control" type="text" name="titulo" placeholder="Ingresar el nombre del producto." value="{{producto.titulo.title}}" required>
        </div>

        <div class="row container mx-auto p-0 pt-3">
            <div class="col-md-6 p-0 m-0">
                <div class="form-group">
                    <label for="imagen" style="color: white;">Imagen producto</label>
                    <input style="color: white;" type="file" class="form-control-file" name="imagen" id="imagen"
                        placeholder="Ingresar la imagen." required>
                </div>
            </div>

            <div class="col-md-6 p-0 m-0 row">
                <div class="col-12 p-0 form-group">
                    <select class="custom-select" name="categoria" required>
                        <option value="" selected>-- Seleccione la categoria --</option>
                        {% for categoria in categorias %}
                            <option value="{{ categoria.id }}">{{ categoria.descripcion }}</option>
                        {% endfor %}
                    </select>
                </div>

                <div class="col-12 p-0 form-group mb-3">
                    <textarea class="form-control" name="descripcion" rows="3" required>{{producto.descripcion.capitalize}}</textarea>
                </div>

                <div class="col-12 ">
                    <div class="row justify-content-between align-items-center">
                        <div class="col-auto m-0 p-0">
                            <div class="input-group">
                                <div class="input-group-prepend">
                                    <div class="input-group-text">Precio: $</div>
                                </div>
                                <input type="number" class="form-control" name="precio" placeholder="XXXX.XX" value="{{ producto.precio|floatformat }}" required>
                            </div>
                        </div>

                        <div class="form-group col-md-4 col-lg-3 m-0 p-0 mt-2 mt-lg-0">
                            <button type="submit" class="btn btn-success btn-block" style="background-color: black;">Editar</button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </form>

</section>
{% endblock %}

core/templates/core/producto/index.html
{% extends "core/layout.html" %}

{% load static %}

{% block content %}
        <div class="row row-cols-1 row-cols-md-3 container justify-content-center">
            {% for producto in productos %}
                <div class="col-6 col-md-3 mb-4">
                    <div class="card h-100 card-img-producto-home">
                        <img 
                        class="card-img-top mx-auto"
                        
                        src="{{MEDIA_URL}}{{producto.imagen.url}}"
                        alt="ultimo producto"
                        >
                        <div class="card-body text-center">
                            <h4 class="card-title">{{ producto.titulo.title|truncatechars:28 }}</h4>
                            <p class="card-text ">{{ producto.descripcion.capitalize|truncatechars:50 }}</p>
                            <a href="{% url 'CORE:producto_show' producto.id %}" class="btn btn-success btn-block">Ver</a>

                            {% if user.is_superuser %}
                                <a href="{% url 'CORE:producto_edit' producto.id %}" class="btn btn-outline-secondary btn-block">Editar</a>
                                <a href="{% url 'CORE:producto_delete' producto.id %}" class="btn btn-outline-danger btn-block">Eliminar</a>
                            {% endif %}

                        </div>
                    </div>
                </div>

            {% empty %}
            <div class="col-12 p-0 m-0">
                No hay productos agregados
            </div>

            {% endfor %}
        </div>
    </div>

{% endblock %}

core/templates/core/producto/search.html
{% extends "core/layout.html" %}

{% load static %}

{% block content %}
<div class="row mt-5">

    <div class="row row-cols-1 row-cols-md-3 container justify-content-center">

        {% for producto in productos %}
            <div class="col-6 col-md-4 col-lg-3 mb-4">
                <div class="card h-100 card-img-producto-home">
                    <img 
                    class="card-img-top mx-auto"
                    src="{{MEDIA_URL}}{{producto.imagen.url}}"
                    alt="{{producto.titulo}}"
                    >
                    <div class="card-body text-center">
                        <h4 class="card-title">{{ producto.titulo.title|truncatechars:30 }}</h4>
                        <p class="card-text ">{{ producto.descripcion.capitalize|truncatechars:50 }}</p>
                        <a href="{% url 'CORE:producto_show' producto.id %}" class="btn btn-success btn-block">Ver</a>

                        {% if user.is_superuser %}
                            <a href="{% url 'CORE:producto_edit' producto.id %}" class="btn btn-outline-secondary btn-block">Editar</a>
                            <a href="{% url 'CORE:producto_delete' producto.id %}" class="btn btn-outline-danger btn-block">Eliminar</a>
                        {% endif %}
                        
                    </div>
                </div>
            </div>
        {% empty %}
        <h2 class="col-12 display-4 text-center mt-5" style="font-size: 2em; height: 30vh;">No hay productos que coincidan</h2>
        {% endfor %}
    </div>
</div>
{% endblock %}

core/templates/core/producto/show.html
{% extends "core/layout.html" %}

{% load static %}

{% block content %}
<div class="row my-5 container">

    <div class="col-10 mx-auto">
        <div class="row border">

            <div class="col-md-5 p-0 ">
                <img style="color: white;" src="{{MEDIA_URL}}{{producto.imagen.url}}" alt="{{producto.titulo}}" class="img-fluid w-100">
            </div>

            <div class="col-md-7 p-4 d-flex flex-column justify-content-between">
                <div class="detalle-producto-content__text">
                    <h1 style="color: white;" class="display-4 text-capitalize">{{ producto.titulo }}</h1>

                    <h2 style="color: white;" class="display-4 text-capitalize mb-3">Categoria: {{ producto.categoria.descripcion }}</h2>

                    <p style="color: white;">{{ producto.descripcion.capitalize }}</p>
                </div>

                <div class="d-flex justify-content-between align-items-center">
                    <p style="color: white;"  class="m-0">
                        <strong style="color: white;" >Precio:</strong>
                        ${{ producto.precio }}
                    </p>
                    <form action="{% url 'CORE:carrito_save' %}" method="POST">
                        {% csrf_token %}
                        <input type="hidden" name="producto_id" value="{{ producto.id }}">
                        {% if user.is_superuser or not user.is_authenticated %}
                            <button type="submit" class="btn btn-success" disabled>Agregar al carrito</button>
                        {% else %}
                            <button type="submit" class="btn btn-success" >Agregar al carrito</button>
                        {% endif %}
                    </form>
                </div>
            </div>

        </div>
    </div>

</div>
{% endblock %}