TestDjango/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('core.urls')), 
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path
from . import views

app_name = "CORE"

urlpatterns = [
    # PRODUCTOS
    path('', views.producto_index, name="producto_index"), #PAGINA PRINCIPAL
    path('producto/agregar', views.producto_create, name="producto_create" ),
    path('producto/<int:producto_id>', views.producto_show, name="producto_show" ),
    path('producto/<int:producto_id>/editar', views.producto_edit, name="producto_edit" ),
    path('producto/<int:producto_id>/eliminar', views.producto_delete, name="producto_delete" ),
    path('producto/buscador', views.producto_search, name="producto_search"),
    path('categoria/<int:categoria_id>/productos', views.productos_por_categoria, name="productos_por_categoria"),

    # REGISTRAR USUARIO
    path('registrarse/', views.register, name="register"),

    # CARRITO
    path('carrito/', views.carrito_index, name="carrito_index"),
    path('carrito/agregar', views.carrito_save, name="carrito_save"),
    path('carrito/clean', views.carrito_clean, name="carrito_clean"),
    path('item_carrito/<int:item_carrito_id>/eliminar', views.item_carrito_delete, name="item_carrito_delete"),

    path('compras', views.compras, name='compras'),
]

core/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Categoria(models.Model):
    id = models.IntegerField(primary_key=True, verbose_name='Id de categoria')
    descripcion = models.CharField(max_length=200, null=True)

    def __str__(self) -> str:
        return f"Id: {self.id} | Descripcion: {self.descripcion}"


class Producto(models.Model):
    id = models.IntegerField(primary_key=True, verbose_name='Id de producto')
    titulo = models.CharField(max_length=50, null=False)
    # Imagen
    imagen = models.FileField(upload_to='productos/')
    descripcion = models.CharField(max_length=200, null=False)
    precio = models.DecimalField(null=False, max_digits=10, decimal_places=2)
    # FK
    categoria = models.ForeignKey(Categoria,on_delete=models.CASCADE, related_name="productos")

    def __str__(self) -> str:
        return f"Id: {self.id} | Titulo: {self.titulo} | Imagen: {self.imagen} | Descripcion: {self.descripcion} | Precio: {self.precio} || Categoria_id: {self.categoria.id} "


class Carrito(models.Model):
    id = models.IntegerField(primary_key=True, verbose_name='Id de carrito')
    usuario = models.ForeignKey(User, on_delete=models.CASCADE, related_name="carrito")
    total = models.DecimalField(null=False, max_digits=10, decimal_places=2)

    def __str__(self) -> str:
        return f"Id: {self.id} | Usuario_id: {self.usuario.id} | Usuario: {self.usuario.username} | Total: {self.total}"


class Carrito_item(models.Model):
    id = models.IntegerField(primary_key=True, verbose_name='Id de Item carrito')
    producto = models.ForeignKey(Producto, on_delete=models.CASCADE) 
    carrito = models.ForeignKey(Carrito, on_delete=models.CASCADE, related_name="items")

    def __str__(self) -> str:
        return f"Id: {self.id} | Producto: {self.producto.titulo} | Carrito_id: {self.carrito.id}"


class Suscripcion(models.Model):
    usuario = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='Suscripcion')
    vigencia = models.BooleanField(default=False) 

    def str(self) -> str:
        return f"Id: {self.pk} | Usuario_id: {self.usuario.id} | User: {self.usuario.username} | Vigencia: {self.vigencia}" 

class Compras(models.Model):
    usuario = models.ForeignKey(User, on_delete=models.CASCADE, related_name= "compras")
    total = models.DecimalField(null=False, max_digits=12, decimal_places=2)
    estado = models.CharField(max_length=100, null=False)

    def str(self) -> str:
        return f"Id: {self.pk} | Usuario_id: {self.usuario.id} | User: {self.usuario.username} | Total: {self.total}  | Estado: {self.estado}"

class Venta_item(models.Model):
    producto = models.ForeignKey(Producto, on_delete=models.CASCADE)
    compras = models.ForeignKey(Compras,on_delete=models.CASCADE ,related_name="items_compras") 

    def str(self) -> str:
        return f"Id: {self.pk} | Producto: {self.producto.titulo} | Compras_id: {self.compras.id}"

core/forms.py
from django import forms
from django.db.models import fields
from .models import Producto
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class UserRegisterForm(UserCreationForm):
    email = forms.EmailField()
    password1 = forms.CharField(widget=forms.PasswordInput)
    password2 = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']

""" 
    PRODUCTO 
"""
class FormProducto(forms.ModelForm):

    class Meta:
        model = Producto
        fields = ('titulo','imagen','descripcion','precio','categoria')
        """ widgets = {
            'titulo': forms.TextInput(),
            'descripcion' : forms.Textarea(),
            'precio' : forms.NumberInput(),
            'imagen' : forms.FileField()
        } """
        """ widgets = {
            'titulo': forms.TextInput(attrs={'class': 'form-control', 'placeholder':'Ingrese el nombre del producto...' , 'required': True}),
            'descripcion' : forms.Textarea(attrs={'class' : 'form-control', 'row' : 3, 'required': True}),
            'precio' : forms.NumberInput(attrs={'class' : 'form-control', 'placeholder':'XXXX.XX', 'required': True}),
            'imagen' : forms.FileField(attrs={'class':'form-control-file', 'id':'imagen', 'placeholder': 'Ingrese la imagen...', 'required': True})
        } """

core/views.py
from django.contrib.auth.models import User
from core.forms import FormProducto
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse
from django.http.response import HttpResponse

from core.models import *
from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages

def register(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            usuario_logeado = User.objects.last()
            messages.success(request, f"El usuario ha sido registrado exitosamente!")
            carrito = Carrito()
            carrito.usuario = usuario_logeado
            carrito.total = 0
            carrito.save()
            suscripcion = Suscripcion()
            suscripcion.usuario = usuario_logeado
            suscripcion.vigencia = False
            suscripcion.save()
            return redirect('CORE:producto_index')
        else:
            messages.success(request, "No se pudo registrar el usuario, vuelva a intenarlo!")

    return render(request, 'registration/register.html')

def producto_index(request):
    productos = Producto.objects.all().order_by("-id")
    
    return render(request, "core/producto/index.html", {
        'categorias' : Categoria.objects.all(),
        #'productos' : productos[3:10] codigo para obtener solo algunos
        'productos' : productos
    })

def producto_create(request):
    categorias = Categoria.objects.all()
    if request.method == "POST":
        categoria_del_producto = Categoria.objects.get(id=request.POST["categoria"])
        form = FormProducto(request.POST, request.FILES, instance=Producto(imagen=request.FILES['imagen'], categoria=categoria_del_producto))   
        if form.is_valid():
            form.save()
            return redirect("CORE:producto_index")
        else:
            return render(request, 'core/producto/create.html', {
                'categorias' : categorias,
                'error_message' : 'Ingreso un campo incorrecto, vuelva a intentar'
            })
    else:
        return render(request, 'core/producto/create.html', {
            'categorias' : categorias
        })

def producto_show(request, producto_id):
    producto =  get_object_or_404(Producto, id=producto_id)

    return render(request, 'core/producto/show.html',{
        'categorias' : Categoria.objects.all(),
        'producto' : producto
    })

def producto_edit(request, producto_id):
    categorias = Categoria.objects.all()
    producto = Producto.objects.get(id=producto_id)

    if request.method == "POST":
        categoria_del_producto = Categoria.objects.get(id=request.POST["categoria"])
        form = FormProducto(request.POST, request.FILES, instance=Producto(imagen=request.FILES['imagen'], categoria=categoria_del_producto))   
        if form.is_valid():
            producto.titulo = request.POST['titulo']
            producto.categoria = categoria_del_producto
            producto.descripcion = request.POST['descripcion']
            producto.imagen = request.FILES['imagen']
            producto.precio = request.POST['precio']
            producto.save()
            return redirect("CORE:producto_index")
        else:
            return render(request, 'core/producto/edit.html', {
                'categorias' : categorias,
                'error_message' : 'Ingreso un campo incorrecto, vuelva a intentar'
            })
    else:
        return render(request, 'core/producto/edit.html',{
            'categorias' : categorias,
            'producto' : producto
        })

def producto_delete(request, producto_id):
    producto = Producto.objects.get(id=producto_id)
    producto.delete()
    return redirect('CORE:producto_index')

def producto_search(request):
    texto_de_busqueda = request.GET["texto"]
    productosPorTitulo = Producto.objects.filter(titulo__icontains = texto_de_busqueda).all()
    productosPorDescripcion = Producto.objects.filter(descripcion__icontains = texto_de_busqueda).all()
    productos = productosPorTitulo | productosPorDescripcion
    return render(request, 'core/producto/search.html',
    {
        'categorias' : Categoria.objects.all(),
        'productos' : productos
    })
  
def productos_por_categoria(request, categoria_id):
    categoria = get_object_or_404(Categoria, id = categoria_id)
    productos = categoria.productos.all()
    return render(request, 'core/producto/search.html',
    {
        'categorias' : Categoria.objects.all(),
        'productos' : productos,
        'categoria' : categoria.descripcion,
    })

def carrito_index(request):
    categorias = Categoria.objects.all()
    usuario_logeado = User.objects.get(username=request.user)
    productos = Carrito.objects.get(usuario=usuario_logeado.id).items.all()

    carrito = Carrito.objects.get(usuario=usuario_logeado.id)
    nuevo_precio_Carrito = 0
    for item in carrito.items.all():
        #validar si es que tiene descuento
        nuevo_precio_Carrito += item.producto.precio

    carrito.total = nuevo_precio_Carrito
    carrito.save()

    if request.method == 'POST':
        compras = Compras()
        compras.usuario = usuario_logeado
        compras.total = carrito.total
        compras.estado = 'Compra confirmada'
        compras.save()

        for item in carrito.items.all():
            producto = Producto.objects.get(id=item.id)
            item_compras = Venta_item()
            item_compras.compras = compras
            item_compras.producto = producto
            item_compras.save()

    carrito.items.all().delete()
    carrito.total = 0
    carrito.save()

    messages.success(request, f"Compra finalizada.")

    return render(request, 'core/carrito/index.html', {
        'categorias' : categorias,
        'usuario' : usuario_logeado,
        'items_carrito' : productos
    })

def carrito_save(request):

    if request.method == 'POST':
        producto = Producto.objects.get(id=request.POST['producto_id'])
        usuario_logeado = User.objects.get(username=request.user)

        #Agregamos el producto
        carrito = Carrito.objects.get(usuario=usuario_logeado.id)
        item_carrito = Carrito_item()
        item_carrito.carrito = carrito
        item_carrito.producto = producto
        item_carrito.save()

        #Sumamos el precio
        carrito.total = producto.precio + carrito.total
        carrito.save()
        messages.success(request, f"El producto {producto.titulo} fue agregado al carrito")
        return redirect("CORE:producto_index")

    else:
        return redirect("CORE:producto_index")

def carrito_clean(request):
    usuario_logeado = User.objects.get(username=request.user)
    carrito = Carrito.objects.get(usuario=usuario_logeado.id)
    carrito.items.all().delete()
    carrito.total = 0
    carrito.save()
    return redirect('CORE:carrito_index')

def item_carrito_delete(request, item_carrito_id):
    item_carrito = Carrito_item.objects.get(id=item_carrito_id)
    carrito = item_carrito.carrito
    
    nuevo_precio_Carrito = 0 - item_carrito.producto.precio
    for item in carrito.items.all():
        nuevo_precio_Carrito += item.producto.precio

    carrito.total = nuevo_precio_Carrito
    item_carrito.delete()
    carrito.save()
    return redirect("CORE:carrito_index")



def compras(request):
    usuario_logeado = User.objects.get(username=request.user)
    compras = usuario_logeado.compras.all

    return render(request, 'core/carrito/compras.html',
    {
        'compras' : compras
    })

core/templates/core/layout.html
{% load static %}

<!doctype html>
<html lang="es">

<head>
    <title>Pet Society</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

</head>

<body style="background-color: rgb(55, 147, 175);">
    <div class="container-sm">
        <div class="row">
            <!-- Columnas deben sumar 12 en total, utilizamos una de 4 -->
            <div style="color: white;" class="col-6 d-flex align-items-center justify-content-center"> 
                <p style="padding-top: 7px;"> <a href="{% url 'CORE:producto_index' %}" style="color: white; font-size: 45px; font-family: 'Brush Script MT', cursive;"> Pet Society </a></p>
            </div>
            <div class="col-6"> 
                <div class="row">
                    <div class="col-10">
                        {% if user.is_authenticated %}
                       <p style="color: white; font-size: 20px;">Welcome to Pet Society {{ user.username }} </p> 
                       <a type="button" class="btn btn-primary" href="{% url 'logout'%}?next=/" style="background-color: black;"> Cerrar sesion </a>

                        {% else %}
                        <div class="row"  style="padding-top: 23px;">
                            <div class="col">
                                <a type="button" class="btn btn-primary" href="{% url 'login'%}?next={{request.path}}" style="background-color: black;"> Iniciar sesion </a>
                            </div>
                            <div class="col">
                                <a type="button" class="btn btn-primary" href="{% url 'CORE:register' %}" style="background-color: black;"> Registrarse</a>
                            </div>
                        </div>
                        {% endif %}
                    </div>
                    <div class="col-2" style="padding-top: 23px;">
                        {% if user.is_superuser or not user.is_authenticated %}
                            <button type="button" class="btn btn-secondary" disabled style="background-color: black;"> Carrito </button>
                        {% else %}
                            <a type="button" class="btn btn-secondary" href="{% url 'CORE:carrito_index' %}"> Carrito </a>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>

        <!-- DIV PARA LA NAVEGACION-->
        <div class="row" >
            <div class="col">
                <nav class="navbar navbar-expand-lg navbar-light bg-light" >
                    <div class="collapse navbar-collapse" id="navbarSupportedContent" >
                      <ul class="navbar-nav mr-auto" >
                        <li class="nav-item active">
                          <a class="nav-link" href="/" style="font-family: Garamond, serif; font-size: 17px;">Home <span class="sr-only">(current)</span></a>
                        </li>
                        <li class="nav-item dropdown">
                          <a style="font-family:garamond,serif; font-size: 17px;" class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"  >
                            Categorias
                          </a>
                          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                            {% for categoria in categorias %}
                            <a class="dropdown-item" href="{% url 'CORE:productos_por_categoria' categoria.id %}">{{ categoria.descripcion.capitalize }}</a>
                            {% endfor %}
                          </div>
                        </li>
                        <li class="nav-item active">
                            <a style="font-family:garamond,serif; font-size: 17px;" class="nav-link" href="{% url 'CORE:compras' %}">Compras <span class="sr-only">(current)</span></a>
                          </li>
                        
                        <!-- AGREGAR PRODUCTO (SOLO ADMINISTRADORES) -->
                        {% if user.is_superuser %}
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'CORE:producto_create' %}" style="font-family:garamond,serif; font-size: 17px;">Agregar producto</a>
                        </li>
                        {% endif %}
                        
                      </ul>
                    </div>
                  </nav>
            </div>  
        </div>
        <br>
        <!-- DIV PARA EL CONTENIDO-->
        <div class="row">
            <div class="col">
                {% block content %}
                {% endblock %}           
            </div>
        </div>
        <footer style="background-color: white; font-family: Garamond, serif;">@Todos los derechos reservados Pet Society</footer>
        
        
    
    <!-- Cierre container-->
    </div>


    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>

</html>